In [21]:
import requests
import pandas as pd
import numpy as np

from geopy.geocoders import Nominatim

In [12]:
address = ['Oakland, California', 'San Francisco, California', 'Seattle, Washington', 'Portland, Oregon']

geolocator = Nominatim(user_agent="Moving_explorer")

locationList = []
for name in address:
    location = geolocator.geocode(name)
    latitude = location.latitude
    longitude = location.longitude
    locationList.append((name, latitude, longitude))
print( locationList )

[('Oakland, California', 37.8044557, -122.2713563), ('San Francisco, California', 37.7790262, -122.4199061), ('Seattle, Washington', 47.6038321, -122.3300624), ('Portland, Oregon', 45.5202471, -122.6741949)]

In [4]:
CLIENT_ID =  'YZEMW4RXCVSXQQKGKONVSMWK301EBWJTWK5IMTDG1TWUNN0B' # your Foursquare ID
CLIENT_SECRET = '4RW5G3QZWDJPNBXGTZSBX10YA4DCMTPUMFUPEKHMROUTYWPA'# your Foursquare Secret
VERSION = '20180605' # Foursquare API version

In [5]:
LIMIT = 100 # limit of number of venues returned by Foursquare API

radius = 500
def getNearbyVenues(locationList):
    
    venues_list=[]
    for name, lat, lng in locationList:
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['City', 
                  'Latitude', 
                  'Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [78]:
venues = getNearbyVenues(locationList)
venues.head()

Oakland, California
San Francisco, California
Seattle, Washington
Portland, Oregon

,City,Latitude,Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,"Oakland, California",37.804456,-122.271356,Oaklandish,37.805075,-122.270726,Clothing Store
1,"Oakland, California",37.804456,-122.271356,Golden Lotus Vegetarian Restaurant,37.803290,-122.270473,Vegetarian / Vegan Restaurant
2,"Oakland, California",37.804456,-122.271356,Bar Shiru,37.806378,-122.270393,Bar
3,"Oakland, California",37.804456,-122.271356,Cafe Van Kleef,37.806660,-122.270273,Bar
4,"Oakland, California",37.804456,-122.271356,Cape & Cowl,37.806725,-122.272747,Comic Shop

In [83]:
generalize_map={'American Restaurant': 'Restaurant', 
                'Antique Shop':'Antique Shop', 
                'Art Gallery': 'Arts Venue', 
                'Art Museum': 'Arts Venue', 
                'Arts & Crafts Store':'Hobby', 
                'Asian Restaurant': 'Restaurant', 
                'BBQ Joint': 'Restaurant', 
                'Bagel Shop': "Cafe", 
                'Bakery':"Cafe", 
                'Bar': "Bar", 
                'Beer Bar': 'Bar', 
                'Bike Shop': 'Hobby', 
                'Bookstore': 'Hobby', 
                'Boutique':'Clothing Store', 
                'Brazilian Restaurant': 'Restaurant', 
                'Breakfast Spot': 'Restaurant', 
                'Brewery': 'Bar', 
                'Bubble Tea Shop':"Cafe", 
                'Building':'Building', 
                'Burger Joint': 'Restaurant', 
                'Butcher':'Groceries', 
                'Caf√©':"Cafe", 
                'Cambodian Restaurant': 'Restaurant', 
                'Caribbean Restaurant': 'Restaurant', 
                'Chinese Restaurant': 'Restaurant', 
                'Chocolate Shop':'Chocolate Shop', 
                'Clothing Store':'Clothing Store', 
                'Cocktail Bar':'Bar', 
                'Coffee Shop':"Cafe", 
                'College Bookstore':'Hobby', 
                'Comedy Club': 'Arts Venue', 
                'Comic Shop': 'Hobby', 
                'Concert Hall':'Arts Venue', 
                'Convenience Store': 'Convenience Store', 
                'Credit Union':'Bank', 
                'Cupcake Shop': 'Cupcake Shop', 
                'Dance Studio': 'Hobby', 
                'Deli / Bodega': 'Restaurant', 
                'Department Store':'Department Store', 
                'Dessert Shop': 'Cafe', 
                'Dim Sum Restaurant': 'Restaurant', 
                'Diner': 'Restaurant', 
                'Dive Bar':'Bar', 
                'Donut Shop':'Cafe', 
                'Dumpling Restaurant': 'Restaurant', 
                'Electronics Store': 'Hobby', 
                'Event Space':'Event Space', 
                'Farmers Market': 'Groceries', 
                'Food & Drink Shop': 'Restaurant', 
                'Food Court': 'Restaurant', 
                'Food Truck': 'Restaurant', 
                'Fountain':'Sightseeing', 
                'French Restaurant': 'Restaurant', 
                'Fried Chicken Joint': 'Restaurant', 
                'Furniture / Home Store': 'Furniture / Home Store', 
                'German Restaurant': 'Restaurant', 
                'Gift Shop': 'Gift Shop', 
                'Gym': 'Hobby', 
                'Gym / Fitness Center': 'Hobby', 
                'Historic Site': 'Sightseeing', 
                'Hot Dog Joint': 'Restaurant', 
                'Hotel': 'Hotel', 
                'Hotel Bar':'Bar', 
                'Ice Cream Shop': 'Cafe', 
                'Indian Restaurant': 'Restaurant', 
                'Indie Movie Theater':'Arts Venue', 
                'Indie Theater': 'Arts Venue', 
                'Irish Pub':'Bar', 
                'Italian Restaurant': 'Restaurant', 
                'Japanese Restaurant': 'Restaurant', 
                'Jazz Club':'Arts Venue', 
                'Jewelry Store': 'Jewelry Store', 
                'Juice Bar':"Cafe", 
                'Latin American Restaurant': 'Restaurant', 
                'Lounge':'Bar', 
                'Market': 'Market', 
                'Mediterranean Restaurant': 'Restaurant', 
                "Men's Store":'Clothing Store', 
                'Mexican Restaurant': 'Restaurant', 
                'Mini Golf': 'Hobby', 
                'Mongolian Restaurant': 'Restaurant', 
                'Music School': 'Hobby', 
                'Music Venue':'Arts Venue', 
                'New American Restaurant': 'Restaurant', 
                'Nightclub':'Bar', 
                'Noodle House': 'Restaurant', 
                'North Indian Restaurant': 'Restaurant', 
                'Opera House':'Arts Venue', 
                'Optical Shop': 'Hobby', 
                'Organic Grocery':'Groceries', 
                'Park':'Sightseeing', 
                'Pedestrian Plaza':'Sightseeing', 
                'Performing Arts Venue': 'Arts Venue', 
                'Pet Store':'Pet Store', 
                'Pharmacy':'Pharmacy', 
                'Pizza Place': 'Restaurant', 
                'Playground':'Playground', 
                'Plaza':'Sightseeing', 
                'Poke Place': 'Restaurant', 
                'Pub':'Bar', 
                'Ramen Restaurant': 'Restaurant', 
                'Recreation Center': 'Hobby', 
                'Restaurant': 'Restaurant', 
                'River':'Sightseeing', 
                'Rock Club':'Arts Venue', 
                'Sake Bar':'Bar', 
                'Salad Place': 'Restaurant', 
                'Salon / Barbershop':'Salon', 
                'Sandwich Place': 'Restaurant', 
                'Scenic Lookout':'Sightseeing', 
                'Seafood Restaurant': 'Restaurant', 
                'Shipping Store': 'Shipping Store', 
                'Shoe Store':'Clothing Store', 
                'Social Club': 'Hobby', 
                'Southern / Soul Food Restaurant': 'Restaurant', 
                'Sporting Goods Shop':'Sporting Goods Shop', 
                'Sports Bar':'Bar', 
                'Steakhouse': 'Restaurant', 
                'Street Food Gathering': 'Restaurant', 
                'Sushi Restaurant': 'Restaurant', 
                'Taco Place': 'Restaurant', 
                'Tapas Restaurant': 'Restaurant', 
                'Tea Room':"Cafe", 
                'Thai Restaurant': 'Restaurant', 
                'Theater': 'Arts Venue', 
                'Thrift / Vintage Store':'Antique Shop', 
                'Tiki Bar':'Bar', 
                'Tour Provider': 'Sightseeing', 
                'Toy / Game Store': 'Hobby', 
                'Vegetarian / Vegan Restaurant': 'Restaurant', 
                'Vietnamese Restaurant': 'Restaurant', 
                'Wine Bar':'Bar', 
                'Wine Shop':'Bar', 
                "Women's Store":'Clothing Store', 
                'Yoga Studio': 'Hobby'
}

In [85]:
#venues = pd.read_csv('./venues_backup.csv')
venues['Venue Category'] = venues['Venue Category'].apply(lambda x: generalize_map[x])
venues.head()

,Unnamed: 0,City,Latitude,Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,0,"Oakland, California",37.804456,-122.271356,Oaklandish,37.805075,-122.270726,Clothing Store
1,1,"Oakland, California",37.804456,-122.271356,Golden Lotus Vegetarian Restaurant,37.803290,-122.270473,Restaurant
2,2,"Oakland, California",37.804456,-122.271356,Bar Shiru,37.806378,-122.270393,Bar
3,3,"Oakland, California",37.804456,-122.271356,Cafe Van Kleef,37.806660,-122.270273,Bar
4,4,"Oakland, California",37.804456,-122.271356,Cape & Cowl,37.806725,-122.272747,Hobby

In [94]:
# one hot encoding
venues_onehot = pd.get_dummies(venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
venues_onehot['City'] = venues['City'] 

# move neighborhood column to the first column
fixed_columns = [venues_onehot.columns[-1]] + list(venues_onehot.columns[:-1])
venues_onehot = venues_onehot[fixed_columns]

#toronto_onehot.head()

#Process data frame for kmeans 
venues_grouped = venues_onehot.groupby('City').mean().reset_index()
venues_grouped.columns.shape

(28,)

In [ ]:
#venues_grouped.to_csv('./venues_freq.csv')

In [87]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [88]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['City']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
city_venues_sorted = pd.DataFrame(columns=columns)
city_venues_sorted['City'] = venues_grouped['City']

for ind in np.arange(venues_grouped.shape[0]):
    city_venues_sorted.iloc[ind, 1:] = return_most_common_venues(venues_grouped.iloc[ind, :], num_top_venues)
city_venues_sorted.head()

,City,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Oakland, California",Restaurant,Bar,Cafe,Hobby,Arts Venue,Clothing Store,Groceries,Cupcake Shop,Sporting Goods Shop,Event Space
1,"Portland, Oregon",Restaurant,Hotel,Cafe,Bar,Hobby,Sightseeing,Clothing Store,Arts Venue,Jewelry Store,Sporting Goods Shop
2,"San Francisco, California",Restaurant,Cafe,Bar,Arts Venue,Hobby,Sightseeing,Clothing Store,Hotel,Groceries,Chocolate Shop
3,"Seattle, Washington",Restaurant,Cafe,Bar,Sightseeing,Hotel,Hobby,Arts Venue,Antique Shop,Building,Convenience Store

In [92]:
venues_cityIndex = venues_grouped.set_index("City")
#print( list(venues_grouped.columns) )
preferences =[]
for category in list(venues_cityIndex.columns): 
    preferences.append( np.random.randint(1,11)/10. )
#print( preferences )
#venues_cityIndex.head()

In [90]:
def cosine_similarity( w, x, y ):
    x_w = w*x
    y_w = w*y
    
    top = np.dot( x_w, y_w)
    bottom = np.linalg.norm(x_w) * np.linalg.norm(y_w)
    
    return top/bottom


print( cosine_similarity( preferences, venues_cityIndex.loc['Oakland, California'], venues_cityIndex.loc['Oakland, California']))

1.0

In [91]:
for city in address[1:]:
    print( '{}: {}'.format(city, cosine_similarity( preferences, venues_cityIndex.loc['Oakland, California'], venues_cityIndex.loc[city])))

San Francisco, California: 0.8395351383115175
Seattle, Washington: 0.9079679814845572
Portland, Oregon: 0.9327001397403365